### ISSUE TITLE
[병준님] BOJ-14467, 20546, 1913, 17276, 14719 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#1]
전반적으로 너무 잘 푸셔서 딱히 드릴 말씀이 없네요.  
병준님께서는 문제 풀이에 시간 제한을 두고, 그 안에 해결하기 위해 타임 어택으로 하시는 게 좋을 것 같습니다.  
만약 잘 안 된다면, 기출을 반복해서 풀어보시면서 아예 풀이 구조를 본인만의 스타일로 정형화하시는 게 지금 상황에서 가장 효율적일 거 같아요.  
이런 공부법을 선호하진 않지만, 기업 코테는 이런 방식이 최선이라는 게 좀 안타깝네요. ㅜ. 

<br/>

## BOJ-14467. [소가 길을 건너간 이유](https://github.com/psychology50/coding-test-study/blob/main/byungjun/boj-14467/BOJ14467.py)
- 배열을 `-1`로 초기화함으로써, 처음으로 소의 입력을 받는 경우를 판단하는 방법이 좋았습니다. 

## BOJ-20546. [기적의 매매법](https://github.com/psychology50/coding-test-study/blob/main/byungjun/boj-20546/BOJ20546.py)
- wallet 이라는 튜플에 돈과 보유 주식이라는 두 가지 정보를 한 번에 담으면 관리는 편하지만 코드가 길어졌을 때 헷갈릴 수도 있어요.
   + 인덱스로 접근하는 방식, wallet이 보유한 주식 수를 의미하지는 않는 점 등으로 인해, 자칫 혼란을 줄 수도 있기 때문에 반드시 하나의 변수로 관리하는 게 능사는 아니더라구요. 개인적인 경험담입니다. ㅎㅎ
- 55번 째 줄의 `JH_wallet[0] > stock and JH_wallet[0] > 0`에서 두 번째 조건식이 반드시 필요할까라는 의문이 들어요.
   + 제가 찾지 못한 이유가 있는 걸까요?
   + stock이 양의 정수이므로 0이 들어오는 경우를 예외처리 하기 위해 `stock > 0`으로 예외를 걸러냈다면 좀 더 안정적이었을 것 같긴 합니다.
- 코테를 위한 코드를 작성하실 때 단일 책임 원칙을 준수한다는 게 항상 옳지도 않고, 힘든 일이지만 지킬 수 있다면 지켜서 나쁠 건 없습니다.
   + 예를 들어 준현이와 성민이의 매도/매수를 계산하는 로직을 각각의 함수로 분리했다면 코드가 좀 더 읽기 좋아질 것 같아요.
   + 코드 가독성이 좋아지면, 설령 문제가 생기더라도 디버깅을 하기가 굉장히 용이해집니다. 서로 다른 로직이 각자의 작업을 방해할 위험성도 최소화되구요. 

## BOJ-1913. [달팽이](https://github.com/psychology50/coding-test-study/blob/main/byungjun/boj-1913/BOJ1913.py)
- 49번 째 줄에 `snail[row+i*dir][col]`처럼 우선 순위가 다른 연산이 쓰이는 경우, 저는 `row + i*dir`이런 식으로 공백을 주는 편입니다. 시각적으로 곱하기 연산자가 우선 실행되고, 이후에 더하기 연산자가 실행될 것이라는 걸 쉽게 이해할 수 있을 거 같아요.
- 이 문제는 아마 수학적으로 숫자의 배치를 맞추는 방식도 가능은 할 텐데, 굳이 그럴 필요는 없어보이네요. 쉽게 풀 수 있는 문제는 쉽게 풀어버리는 게 베스트라고 생각합니다. 👍

## BOJ-17276. [배열 돌리기](https://github.com/psychology50/coding-test-study/blob/main/byungjun/boj-17276/BOJ17276.py)
```python
   # 회전 횟수
    d = d // 45
    if d > 0:
        d -= 8
    d = abs(d)
```
```python
d = (d // 45) if d >= 0 else (d // 45 + 8)
```
- 개인적으로 전 삼항 연산자를 애용하다 보니, 이 부분을 한 줄로 줄일 수도 있을 것 같아요. 혹여 코드 줄이기에 관심 있으시다면 참고해보세요 ㅋㅋㅋ
- 이 문제처럼 기존의 입력 배열을 수정해야 하는 문제는 그대로 사용하면 오류가 나기 십상입니다. 제출용 n*n배열을 만들어서 그곳에 정답을 입력하면 훨씬 간편하게 해결하실 수 있을 거예요. (temp가 필요 없어지고, 반복문 하나도 덜 쓸 수 있습니다.)
- 굳이 메모리 초과를 신경쓸 정도가 아니라면, 문제는 쉽게쉽게 풀 수 있으면 좋습니다.

## BOJ-14719. [빗물](https://github.com/psychology50/coding-test-study/blob/main/byungjun/boj-14719/BOJ14719.py)
- 병준님께선 while문을 많이 좋아하시네요. ㅋㅋㅋㅋㅋㅋ 이건 진짜진짜진짜 개인 스타일일 수 있지만, 보통 코테를 칠 땐 for문을 쓰는 것을 권장합니다. 왜냐하면, while문은 탈출 조건을 확인하기 위해서 코드 전체를 이해할 필요가 있지만, for문은 첫 시작부터 반복 조건을 한 눈에 파악할 수 있기 때문입니다.
  + 코테 문제를 풀 때도 가독성을 굉장히 중요시 여기기 때문에 계속 강조드리는 내용입니다.
  + 다만 병준님의 아이디어를 기반으로 for문으로 리팩토링을 시도하는 건 좀 힘들 것 같다는 생각이 드네요. 제가 말씀드린 것도 참고로만 봐주세요.
- 지금 풀이하신 방법보다 더 빠른 방법이 있을까요? 
  + 현재 로직은 다소 불필요한 반복이 많긴 합니다.
  + 이 문제를 해결하기 위해 알아야 하는 조건들은 무엇이 있을까요? 저는 `현재 위치`를 기준으로 `왼쪽 벽`과 `오른쪽 벽` 중 더 낮은 벽을 찾아야 한다고 문제를 이해했습니다.
  + 이렇게 접근을 하면 반복문 한 번만으로 잘 해결할 수도 있을 것 같은데, 어떻게 생각하시나요?

**Comment by BangDori** [comment]
## BOJ-20546. 기적의 매매법
1. wallet 튜플로 관리하는 방법 보다는, 돈과 보유 주식을 분리하는 게 좋을 것 같아 분리하였습니다.
   + `JH_wallet` -> `JH_money`, `JH_stocks`
   + 분리하고 코드를 다시 작성해보니, 가독성 측면에서 훨씬 더 좋은 것 같습니다.
2. `JH_wallet[0] > stock and JH_wallet[0] > 0` 이 코드를 처음 작성한 이유는, 주식 가격보다 크고 지갑에 돈이 있을 때를 의미하는 코드였는데, 생각해보니 주가가 음수로 나오는 경우가 없으니 뒤 조건을 지워도 될 것 같습니다.
3. 처음에는 문제가 쉬워서 준현이와 성민이의 매도/매수 계산 로직을 하나의 for문으로 관리하였었는데, 복잡해진다면 로직을 분리하는게 더 좋은 방법이 될 것 같아 준현이와 성민이의 매도 매수를 계산하는 로직을 분리하였습니다.

[수정된 코드](https://github.com/BangDori/python-algorithm/blob/main/study/1/BOJ20546/BOJ20546.py)

## BOJ-1913. 달팽이
1. 우선 순위가 다른 연산이 쓰이는 경우 공백을 주어서 분리하는 것이 좋을 것 같아서 반영하였습니다!

[수정된 코드](https://github.com/BangDori/python-algorithm/blob/main/study/1/BOJ1913/BOJ1913.py#L17)

## BOJ-17276. 배열 돌리기
1. 삼항 연산자를 사용하는 방법을 생각하지 못했었는데, 삼항 연산자를 사용하는 방법이 더 좋을 것 같아서 반영하였습니다.
3. 타이머를 설정하고 푼 문제였는데, 시간안에 푼 방법이라 다음번 문제부터 문제를 풀때에는 제출용 배열을 생성하여 그 곳에 정답을 입력하는 방식으로 풀어보도록 하겠습니다.
4. while문 사용하는 방법을 for문을 사용하여 탈출 조건을 명확하게 하였습니다.

[수정된 코드](https://github.com/BangDori/python-algorithm/blob/main/study/1/BOJ17276/BOJ17276.py)

## BOJ-14719. 빗물
1. while문을 사용하면 indexError 문제, 예측 불가능한 에러가 발생하는 경우가 많았었는데, 다음부터는 for문을 사용하여 탈출 조건을 명확하게 하여 문제를 푸는 방법이 더 좋을 것 같습니다!!! 감사합니다. 🤗
2. "배열을 순회하면서 다음 벽이 증가하는 순간이 기준" 이라고 생각하여서 문제를 해결하였었는데, 만약 `3 2 1 2 1 3` 벽이 이런식으로 오게되면, 기준이 되는 벽을 정확하게 잡아내지 못했었습니다. 그래서 "시간안에 풀자 라는 생각으로 급박하게 풀다 보니 while문을 통해 계속해서 빗물을 채워나가자" 라고 생각했었는데 사실 이 방법은 풀면서 불필요한 코드가 되게 많이 작성되었었는데 재서님이 참고해주신 방법으로 문제를 해결해보았습니다.

[수정된 코드](https://github.com/BangDori/python-algorithm/blob/main/study/1/BOJ14719/BOJ14719.py)

**Comment by psychology50** [comment]
- BOJ-20546. 기적의 매매법
  + 하나의 반복문 안에서 각각 함수를 호출하는 걸 예상했는데, 함수를 아예 분리해버리셨네요. 이것도 좋은 방법인 것 같아요!
  + 사실 이번 문제는 병준님 코드가 훨씬 효율적이었을 수 있습니다. 다만 나중에 코드가 길어지는 문제에서 어려움을 겪으실 수 있을 듯하여 말씀드려본 것이니 참고만 해주세요.

<br/>

수정된 코드 모두 읽어보았습니다! 👍👍  
제 리뷰는 하나의 의견으로만 보고, 병준님 코드 스타일에 맞게 잘 흡수하셨으면 좋겠습니다.  
수고하셨습니다. :)
