### ISSUE TITLE
[재훈님] BOJ-14467, 20546 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#11]
## [BOJ-14467. 소가 길을 건너간 이유](https://github.com/psychology50/coding-test-study/blob/main/jaehoon/boj-14467/B14467.java)
- 변수명을 직관적으로 잘 지으셨어요!
- Java에서 입력/출력을 할 때는 `BufferReader, StringTokenizer`/`StringBuilder`를 많이 사용합니다. 어떻게 사용하는지 알아보세요. 쉬운 문제를 풀 때, 알아두시는 것이 좋습니다.
- 22번 줄의 `if ((cow[cowIndex - 1] != cowLocation) && (cow[cowIndex - 1] != -1))`에서 두 번째 조건은 과연 필요했을까요? 없다면 어떻게 될까요?

## [BOJ-20546. 기적의 매매법](https://github.com/psychology50/coding-test-study/blob/main/jaehoon/boj-20546/S20546.java)
- 아직 통과하지 못한 코드이므로, 아이디어만이라도 블로그에 정리해두시면 리뷰 추가해드리겠습니다.

**Comment by jhoonyeel** [comment]
BOJ-14467
2. 1913문제 풀 때 BufferedReader, StringBuilder 사용했습니당~
3. &&연산을 사용하지 않으면 초기화되지 않은 소까지 계산되기 때문에 &&연산을 필수로 넣어야 합니다!!
BOJ-20546
해결했습니다!!
