### ISSUE TITLE
[민정님] BOJ-14467, 20546 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#2]
블로그에 문제 풀이 정리해주세요~~~~~~~~.  
정리할 때도 고려해야 할 사항들이 있기 때문에 확인해드리려는 거니까 꼭 해주셔야 합니다.  

<br/>

## BOJ-14467. [소가 길을 건너간 이유](https://github.com/psychology50/coding-test-study/blob/main/minjeong😎/boj-14467/Boj14467.java)
- 대면 때 말씀드렸다시피 Scanner를 사용한 입력 방식은 굉장히 느립니다.
  + 지금은 익숙하지 않겠지만, 차라리 쉬운 문제를 푸시는 지금 시기에 StringTokenizer같은 애들한테 익숙해지는 게 좋아요!!!
  + 사용하시는 언어의 라이브러리를 잘 아는 것도 코테의 기본 준비 자세입니다.
- 변수명을 신경 써서 지으신게 보여요. 정말 좋은 자세입니다!!
  + 하지만 입력값으로 n, k, t 등등..이미 문제에서 정해준 변수명은 그대로 사용하시는 게 덜 헷갈릴 수도 있어요.
  + 자바 언어는 `snake_case`가 아니라 `camelCase`로 변수명을 짓는 것을 표준으로 합니다.
- mark라는 배열은 처음 소가 배치되는 경우를 구분하기 위함인 것 같아요! 잘 하셨습니다.
  + 이 외에도 mark 배열을 `-1`로 초기화하는 테크닉도 있습니다. (-1이라면 처음 배치하는 거겠죠?) 방문하지 않은 배열을 어떻게 초기화 하느냐에 따라 다양하게 써먹을 수 있으니 참고해보세요~!

## BOJ-20546. [기적의 매매법](https://github.com/psychology50/coding-test-study/blob/main/minjeong😎/boj-20546/BOJ20546.java)
- 일반적으로 변수명을 대문자로 짓는 것은 상수를 쓸 때만 한정됩니다. 또한 대문자로 네이밍이 시작하는 것은 클래스명에 한정되구요.
- 따라서 `BNP_balance`는 `camelCase`로 `bnpBalance`로 네이밍하는 것이 적절합니다.
- 네이밍 규칙을 준수하지 않는다고 컴파일 에러가 발생하지는 않지만, 개발자 사이의 규칙은 지켜주는 것이 좋습니다.

```java
        for (int i = 0; i < 14; i++) {
					
			if (BNP_balance/cost[i] > 0) {
				int buying = BNP_balance/cost[i];
				BNP_cnt = BNP_cnt + BNP_balance/cost[i];
				BNP_balance = BNP_balance - buying*cost[i];
			}
						
            if (i != 0 && cost[i-1] > cost[i]) {
				down_cnt++;
			} else if (i != 0 && cost[i-1] < cost[i]) {
				up_cnt++;
			}
            
            if (down_cnt >= 3 && TIMING_balance/cost[i] > 0) {
            	int buying = TIMING_balance/cost[i];
				TIMING_cnt = TIMING_cnt + TIMING_balance/cost[i];
				TIMING_balance = TIMING_balance - buying*cost[i];
			} else if (up_cnt >= 3 && TIMING_cnt > 0) {
				TIMING_balance = TIMING_balance + TIMING_cnt*cost[i];
				TIMING_cnt = 0;
			}
            
            if (i != 13 && cost[i] <= cost[i+1]) {
				down_cnt = 0;
			}
            
            if (i != 13 && cost[i] >= cost[i+1]) {
				up_cnt = 0;
			}
            		
		
		}
```
- 해당 반복문은 준현이와 성민이의 주식 투자를 동시에 계산하고 있습니다.
- 물론, 문제는 풀리지만 준현이와 성민이의 주식 투자 계산 로직을 함수로 분리해주는 것이 좋습니다. 왜일까요?
   + 하나의 for문에서 처리를 하면 준현이와 성민이의 계산 로직이 섞여서, 서로 간에 영향을 주게 될 수도 있습니다. 휴먼 에러죠 ㅎㅎ
   + 만약 둘 중 하나가 틀렸을 경우, 코드를 수정해야 하지만 "어디서부터 어디까지가" 준현이와 성민이의 stock 매매 로직인 지 한 눈에 파악이 어렵습니다. 즉, 디버깅도 어렵고 오류 원인을 찾아도 수정이 어려워질 수 있어요.
   + 단일 책임 원칙을 코테에서 모두 적용하기란 힘들고, 때로는 비효율적일 수 있습니다. 하지만 지킬 수 있다면 지켜주는 것이 좋아요!

**Comment by byeon22** [comment]
> ## BOJ-20546. [기적의 매매법](https://github.com/psychology50/coding-test-study/blob/main/minjeong%F0%9F%98%8E/boj-20546/BOJ20546.java)
> * 이 문제는 해결을 하신 건지 아닌지 모호하네요. 디버깅 흔적이 남아있어서, 완성된 코드 올려주시면 리뷰해드리겠습니다. :)

코드 수정했습니당ㅎㅎ 디버깅 코드 뺐어요!
