### ISSUE TITLE
[재훈님] BOJ-20546 코드 리뷰

### ISSUE THREAD

**Issue by jhoonyeel** [psychology50/coding-test-study#20]
``` java
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
int money = Integer.parseInt(br.readLine());

String[] input = br.readLine().split(" ");
int[] chart = new int[14];
for (int i = 0; i < chart.length; i++) {
    chart[i] = Integer.parseInt(input[i]);
}
```
BufferedReader를 위와 같이 사용하니까 런타임 에러가 뜬다...?? 
Scanner를 사용하니 정상적으로 정답 처리가 된다. 왜 이러는거지 ㅠㅠ

**Comment by psychology50** [comment]
본인이 리뷰를 열어버리시면 어떡해요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 전 리뷰한 적이 없는데 뭔가 했습니다.  
제가 리뷰를 열고, 거기에 재훈님이 답이나 질문을 남겨주면 됩니다. 그럼에도 꼭 남겨야 할 말이 있다면, 다른 타이틀을 남겨주세요!!
- 사용하려는 도구가 정상적으로 동작하지 않는 것은, 해당 도구에 대한 이해도가 부족하기 때문에 벌어지는 현상입니다.
   - 단순히 BufferdReader를 입력받는 도구가 아닌, 어떤 원리로 입력을 받고, 왜 Scanner보다 빠른지를 찾아보세요.
   - 현재 문제가 발생하는 원인만 말씀드리자면 가장 처음에 money를 입력받기 위해 br.readLine()을 사용하셨는데, 여기서 잘못 사용하셨기 때문에 두 번째 br.readLine()에 잘못된 값이 넘어갔을 겁니다. (궁금하시면 input 배열을 출력해보세요)
