### ISSUE TITLE
[신얀님] BOJ - 10870 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#22]
### [피보나치 수 5](https://github.com/psychology50/coding-test-study/blob/main/shinyan/boj/10870.swift)
- "코드를 수정하는 것 보다 때로는 생각을 바꿔서 코드를 다시 짜는게 더 효율적인 거 같다" ㅋㅋㅋㅋㅋㅋ 제 주입식 교육이 먹혔네요.
- 피보나치 수열 문제는 재귀 함수의 대표적인 기조 문제입니다.
- `if n<2`라는 탈출 조건을 세우고, 기저 사례를 통한 값을 구하는 방식이예요.
- 신얀님의 최종 코드의 시간 복잡도가 어떻게 된다고 생각하시나요? 블로그를 참조하지 않고 본인의 생각을 말씀해주세요! 틀려도 됩니다.

**Comment by yanni13** [comment]
O(n)이라고 생각됩니다.,

**Comment by psychology50** [comment]
혹시 O(N)이라고 생각하신 이유가 있나요?

**Comment by yanni13** [comment]
반복문도 없고 .. 함수호출을 하고 있으니까 그렇다고 생각했습니다.,.,.,.,.,............
