### ISSUE TITLE
[재훈님] BOJ-2460 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#27]
### [지능형 기차 2](https://github.com/psychology50/coding-test-study/blob/main/jaehoon/boj-2460/B2460.java)
![image](https://github.com/psychology50/coding-test-study/assets/96044622/56c5f79c-5c8b-4302-8315-32f3afd8cd38)
- 최대/최소값을 찾는 여러 가지 방법을 찾아보신 거 잘 하셨어요!
   - `Arrays.sort()`로 구하면 배열을 정렬을 해야 하는데, 해당 메서드의 시간 복잡도가 어떻게 될까요?
   - `max()`, `min()` 메서드는 최대, 최소를 구할 때 많이 사용합니다. ㅎㅎ
   - `stream()`의 경우 사용에 주의해야 합니다. 백준에서는 Java 11 버전으로 컴파일을 하는데, 시험장에서는 몇 버전으로 컴파일 할 지 확신할 수가 없어요. 참고로 Stream은 Java 8 이상부터 사용가능합니다.

**Comment by dekoms** [comment]
문제에서 기차의 정원은 10000명을 초과하지 않는다고 나와있는데 딱히 조건을 걸지 않아도 문제 성공이 뜨네용
``` java
		for (int i = 1; i < 10; i++) {
			total[i] = total[i - 1] - down[i] + up[i];
			if (total[i] > 10000) {
				total[i] = 10000;
			}
		}
```

if문은 필요 없는 건가요??

**Comment by jhoonyeel** [comment]
Array.sort()는 DualPivotQuickSort를 사용하여 평균: nlogn, 최악: n^2의 시간복잡도를 가진다.  알고리즘 시간에 배운 3-way quick sort와 큰 차이 없다! 있다면 pivot의 차이?

**Comment by jhoonyeel** [comment]
문제에서 기차의 정원은 10000명을 초과하지 않는다고 나와있는데 딱히 조건을 걸지 않아도 문제 성공이 뜨네용
``` java
		for (int i = 1; i < 10; i++) {
			total[i] = total[i - 1] - down[i] + up[i];
			if (total[i] > 10000) {
				total[i] = 10000;
			}
		}
```

if문은 필요 없는 건가요??

**Comment by psychology50** [comment]
반례가 존재하지 않는 이상, 굳이 분기 처리를 해줄 이유는 없어보입니다.
