### ISSUE TITLE
[병준님] BOJ-7576, 2636, 2206 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/coding-test-study#32]
문제 드리는 족족 푸시는 거 보고 즐거워서 계속 내드렸다가, 리뷰 쌓인 거 보고 살짝 한숨 한 번 쉬고 시작합니다.
한 번 더 쉬고 시작.

### [토마토](https://github.com/psychology50/coding-test-study/tree/main/byungjun/boj-7576)
- python에서 `deque`는 스택이나 큐처럼 다룰 수 있는 매우 유용한 collection입니다. 꼭 메서드들과 내부 작동 방식을 알아두셔야 해요.
- list에서 `pop()`하면서 O(N) 시간 복잡도가 발생한다는 건 저도 예상치 못한 이슈네요. 생각해보면 당연한 건데, 잊고 살았어요.
- bfs처럼 자명한 알고리즘은 함수로 선언해서 사용하시는 게 좋을 수도 있다는 생각이 들어요.
  - 전체 코드에서 어디서부터 어디까지가 bfs인지가 명확하니 디버깅 관점에서도 이점을 얻을 수 있을 거 같고
  - 솔직히 bfs 쓰면 거기서 거기다보니 전체 틀을 머리에 각인시킬 때, 전역에 늘어놓기 보단 bfs 함수 내에 정의하는 게 좀 더 각인이 될 것 같기도 하구요.
  - 그냥 개인적인 생각입니다. 아무래도 함수로 범위를 한정해야 로직의 순서가 명확하게 드러나서 보기 좋다보니, 저는 함수 선언을 즐기는 스타일이거든요.
- 대부분의 블로그에선 bfs를 공식처럼 외워서 쓰다보니 `visited` 배열을 꼭 만들던데(저도 예전에 그래 놨네요), 병준님은 box 리스트 하나만으로 처리해버리셨네요. 덕분에 코드가 군더더기 없이 깔끔해서 인상깊었습니다.

<br/>

### [치즈](https://github.com/psychology50/coding-test-study/tree/main/byungjun/boj-2636)
- 이 문제 개인적으로 굉장히 좋아하는 문제입니다. 예전에 본인이 bfs를 아주 잘 안다고 자만하던 멘티 한 분의 머리를 박살낸 문제였거든요.
- 원래 모든 문제는 내가 풀 땐 죄다 올림피아드 킬러 문제 같은데, 풀이 보면 기본 문제 같아 보여요. 과학입니다. 
- 특히 이 문제는 "단순히 bfs 써봤냐"가 아닌, 조건을 어떻게 수정해서 문제를 해결할 지 고민해볼 수 있는 아주 좋은 문제예요.
- 혹시 `시간 복잡도`를 구하실 수 있으실까요? bfs의 시간 복잡도는 워낙 널리 알려져 있긴 한데, 병준님의 코드는 얼마나 걸릴까요?

제가 예전에 작성했던 풀이도 첨부해둘 테니, 한 번 병준님 코드와 비교해보세요. (특히 어떤 식으로 치즈가 모두 녹았는 지를 판단하는지)  
사실 너무 옛날 코드라 저도 뭔 생각하고 짰는지 잘 기억 안 납니다.  
한 번 읽어보시고, 뽑아 먹으실 부분은 뽑아 먹으시고, 버릴 부분은 버리셔서 취사 선택하시면 될 것 같습니다.
```python
move = [(-1, 0), (0, 1), (1, 0), (0, -1)]

def bfs(table, row, col):
    queue = [(0, 0)]
    time = 0

    while queue:
        visited = [[0]*col for _ in range(row)]
        cnt = 0
        for y, x in queue:
            if not visited[y][x]:
                visited[y][x] = 1
                for q, p in move:
                    m_y = y + q
                    m_x = x + p
                    if 0 <= m_y < row and 0 <= m_x < col:
                        if table[m_y][m_x] == 0:
                            queue.append((m_y, m_x))
                        else:
                            table[m_y][m_x] = 0
                            visited[m_y][m_x] = 1
                            cnt += 1
        if cnt == 0:
            return time, result
        else:
            result = cnt
            time += 1
            queue.clear()
            queue = [(0, 0)]

def solution():
    row, col = map(int, input().split())
    table = [list(map(int, input().split())) for _ in range(row)]
    
    time, cnt = bfs(table, row, col)
    print(time)
    print(cnt)

solution()
```

<br/>

### [벽 부수고 이동하기](https://github.com/psychology50/coding-test-study/tree/main/byungjun/boj-2206)
- 되게 재밌게 해결하셨네요. 전 진짜 무식하게 벽을 부시면 차원을 이동 시켜버렸던 거 같은데, 지금 생각해보면 이게 통과한 게 웃기네요.
- `visited` 배열을 안 만들고, 기존 배열을 응용해서 풀이를 잘 하시네요. 지금처럼만 잘 다룰 수 있다면 다행이지만, 아무래도 원본 배열을 건드는 건 리스크가 커서 신중히 다루시는 게 좋아요. 물론 너무 잘 하고 계시구요.
![image](https://github.com/psychology50/coding-test-study/assets/96044622/024aae96-095e-407b-bd08-b98e0737e842)
- 제가 기존 배열 잘 안 건드는 이유가 이런 식으로 해결하려고 구상했을 때, 정당성 증명이 너무 어렵거든요. 물론 코딩에 집중할 때 발휘되는 그 직관력으로 해결된다면 다행이지만, 시간이 오래 걸릴 수도 있는 작업이라면 직관에 의존하기엔 위험할 때가 있으니까요.

요것도 코드 첨부해둡니다.
```python
import sys
from collections import deque

input = sys.stdin.readline

def bfs(n, m, board):
    vector = [(-1, 0), (0, 1), (1, 0), (0, -1)]
    visited = [[[0]*2 for _ in range(m)] for _ in range(n)]
    queue = deque()
    
    queue.append([0, 0, 0])
    visited[0][0][0] = 1

    while queue:
        y, x, flag = queue.popleft()
        for q, p in vector:
            m_y = y + q
            m_x = x + p
            if 0 <= m_y < n and 0 <= m_x < m:
                if board[m_y][m_x] == 0 and visited[m_y][m_x][flag] == 0:
                    visited[m_y][m_x][flag] = visited[y][x][flag] + 1
                    queue.append([m_y, m_x, flag])
                if board[m_y][m_x] == 1 and flag == 0:
                    visited[m_y][m_x][flag + 1] = visited[y][x][flag] + 1
                    queue.append([m_y, m_x, 1])
    if visited[n-1][m-1][0] == 0 and visited[n-1][m-1][1] == 0:
        return -1
    elif visited[n-1][m-1][0] == 0:
        return visited[n-1][m-1][1]
    elif visited[n-1][m-1][1] == 0:
        return visited[n-1][m-1][0]
    else:
        return min(visited[n-1][m-1][0], visited[n-1][m-1][1])

def solution():
    n, m = map(int, input().split())
    board = [list(map(int, input().rstrip())) for _ in range(n)]

    print(bfs(n, m, board))

solution()
```

**Comment by BangDori** [comment]
### 토마토

- bfs로 문제를 해결할 때는 함수로 분리하는게 아니라 `main` 소스 코드 내에서 해결을 하다보니 디버깅 과정에서 시간이 많이 소모되었었는데, 함수로 분리해서 문제를 푸는 연습을 해봐야 할 것 같아요!! 감사합니다 😊

### 치즈

- 치즈 문제를 풀지는 못했지만 문제를 이해하고 어떻게든 풀어보려고 많은 노력을 했던 기억이 나요! 다른 분의 코드를 참고해서 문제를 풀기는 했지만, 오랜 시간을 투자해서 문제를 이해하려고 했던 덕분인지 bfs에 대해 더 깊게 이해할 수 있었던 문제인 것 같아요.
- bfs를 이용해서 순회하는 과정에서 `table[m_y][m_x]`가 치즈라면 치즈를 녹여버리는 부분이 인상 깊었어요. 저는 순회를 다 하고 한번에 녹였거든여! 녹이는 부분은 코드를 작성하는 사람에 따라 다르겠지만, 저는 재서님 코드가 더 가독성있고 이해가 잘 되는것 같아요!! 잘 참고하겠습니다 🔥
- 시간복잡도는 제가 계산했을 때, 치즈의 깊이에 달라지는 것 같아서 **O(n^2 * cheeze_depth)** 가 될 것 같아요.

### 벽 부수고 이동하기

- 재서님은  `visited` 배열을 잘 생성해서 사용하시는 것 같아요. 이전까지는 `visited`배열을 사용하지 않고도 해결되는 문제가 많아서 이번에 2020 카카오 인턴십 문제중에 [경주로 건설](https://school.programmers.co.kr/learn/courses/30/lessons/67259) 문제를 해결할 때, `visited` 배열을 생성하지 않고 풀다가 크게 한번 다쳤거든요.
- bfs 문제를 해결할 때 `visited` 배열을 두고 이전에 이동했는지를 검사하는게 시간 효율성과 정확성을 확실하게 잡을 수 있더라구요. 재서님 코드 보면서 `visited` 배열에 대해 한번 더 깊게 생각하게 되네요. 감사합니다 👍👍
